config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'elders#index'

  resources :elders, only: [:show] do
    resources :rents, only: [:create]
  end

  resources :rents, only: [:index] do
    resources :reviews, only: [:new, :create]
  end

  namespace :my do
    resources :elders, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :rents, only: [:index] do
      resources :confirmeds, only: [:create], controller: 'rents/confirmeds'
      resources :declineds, only: [:create], controller: 'rents/declineds'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/elder.rb
class Elder < ApplicationRecord
  belongs_to :user
  has_many :rents, dependent: :destroy
  has_many :users
  has_many :elder_skills, dependent: :destroy
  has_many :skills, through: :elder_skills

  validates :full_name, presence: true, uniqueness: true
  validates :address, presence: true

  mount_uploader :photo, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def average_rating
    ratings = []
    rents.each { |rent| ratings << rent[:rating] if rent[:rating].positive? }
    if ratings.count.positive?
      ratings.inject { |sum, el| sum + el }.to_f / ratings.size
    else
      ''
    end
  end
end

app/models/elder_skill.rb
class ElderSkill < ApplicationRecord
  belongs_to :elder
  belongs_to :skill

  validates :elder, uniqueness: { scope: :skill, message: 'This combination Elder/Skill already exists' }
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :elder

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates_datetime :end_date, after: :start_date
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }

  enum status: { pending: 0, confirmed: 1, declined: 2 }
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :elder_skills

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rents
  has_many :elders

  has_many :bookings, through: :elders, source: :rents

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/elders_controller.rb
class EldersController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  layout 'layout_home', only: [:index]

  def index
    if params[:query].present?
      @elders = Elder.near(params[:query], 15)
    else
      @elders = Elder.where.not(latitude: nil, longitude: nil)
    end

    @markers = @elders.map do |elder|
      { lng: elder.longitude, lat: elder.latitude }
    end
  end

  def show
    @elder = Elder.find(params[:id])
    @rent = Rent.new
  end
end

app/controllers/my/elders_controller.rb
class My::EldersController < ApplicationController
  before_action :set_elder, only: [:show, :edit, :update, :destroy]

  def index
    @elders = Elder.where(user: current_user)
  end

  def new
    @elder = Elder.new
  end

  def create
    @elder = Elder.new(elder_params)
    @elder.user = current_user
    if @elder.save
      redirect_to my_elders_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @elder.update(elder_params)
    redirect_to my_elders_path
  end

  def destroy
    @elder.destroy
    redirect_to my_elders_path
  end

  private

  def set_elder
    @elder = Elder.find(params[:id])
  end

  def elder_params
    params.require(:elder).permit(:full_name, :address, :description, :photo, skill_ids: [])
  end
end

app/controllers/my/rents/confirmeds_controller.rb
class My::Rents::ConfirmedsController < ApplicationController
  def create
    rent = Rent.find(params[:rent_id])
    rent.confirmed!
    redirect_to '/my/rents'
  end
end

app/controllers/my/rents/declineds_controller.rb
class My::Rents::DeclinedsController < ApplicationController
  def create
    rent = Rent.find(params[:rent_id])
    rent.declined!
    redirect_to '/my/rents'
  end
end

app/controllers/my/rents_controller.rb
class My::RentsController < ApplicationController
  def index
    @bookings = current_user.bookings
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  def index
    @rents = Rent.where(user: current_user)
  end

  def new
    @elder = Elder.find(params[:elder_id])
    @rent = Rent.new
  end

  def create
    @rent = Rent.new(rent_params)
    @elder = Elder.find(params[:elder_id])
    @rent.elder = @elder
    @rent.user = current_user
    if @rent.save
      redirect_to rents_path
    else
      render 'elders/show'
    end
  end

  private

  def rent_params
    params.require(:rent).permit(:start_date, :end_date)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @rent = Rent.find(params[:rent_id])
  end

  def create
    @rent = Rent.find(params[:rent_id])
    @rent.update(review_params)
    if @rent.save
      redirect_to rents_path
    else
      render :new
    end
  end

  private

  def review_params
    # TODO : Update this
    params.require(:rent).permit(:review, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/elders/_reviews.html.erb
<div class="inner-container-reviews">
  <div class="image">
    <img src="https://i.pinimg.com/originals/96/e5/9d/96e59d5bd9de9a3d5e510289c7fd64c2.jpg" alt="" class="avatar-large">
  </div>

  <div class="review">
    <div class="review-details">
      <h3>Review from <%= rent.start_date.strftime("%B") %> <%= rent.start_date.year %></h3>
    </div>

    <div class="rating">
      <p>
        <%= '⭐️' * rent.rating %>
      </p>
    </div>

    <div class="review-content">
      <p><%= rent.review %></p>
    </div>

  </div>
</div>

app/views/elders/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.5) 0%, rgba(0,36,61,0.4) 50%), url('https://theinnatlospatios.com/wp-content/uploads/2016/08/4-1-1024x684.jpeg');">
  <div class="banner-content">
    <h1>Grandpa-Rent</h1>
    <h3>Rent your elderly person</h3>
    <p>Your location:</p>
    <%= link_to root_path(query: 'Bordeaux') do %>
      <div class="btn btn-primary cities-btn">Bordeaux</div>
    <% end %>
    <%= link_to root_path(query: 'Paris') do %>
      <div class="btn btn-primary cities-btn">Paris</div>
    <% end %>
  <div class="scroll">
  </div>
    <img src="https://di-uploads-pod4.s3.amazonaws.com/mercedesbenzoffoothillranch/uploads/2016/08/arrow-down.png" style="opacity: 0.3; position: relative; top: 190px;">
  </div>
</div>

<!-- <div class="container"> -->
  <div class="row">
    <div class="col-xs-12 col-md-8">


      <% @elders.each do |elder| %>
        <div class="col-xs-12 col-sm-6 col-md-4 card">

          <div class="card-body">
            <div class="card-tags">
              <% if elder.skills.first.nil? == false %>
                <div class="card_tag">
                  <%= elder.skills.first.name %>
                 </div>
              <% end %>
            </div>
            <%= link_to elder_path(elder) do %>
              <div class="card-picture" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(<%= cl_image_path elder.photo, height: 300, width: 400, crop: :fill, gravity: :face %>);">

              </div>
            <% end %>
              <div class="card-footer">
                <ul class="list-inline">
                  <li class="name"> <%= elder.full_name %></li>
                  <li id="list-rating"><%= elder.average_rating %>
                    <%= elder.average_rating.is_a?(String) ? "" : '⭐️' %>
                  </li>
                </ul>
              </div>
          </div>
        </div>
      <% end %>

    </div>
    <div class="col-xs-12 col-md-4">
      <div
        id="map"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
    </div>
  </div>
<!-- </div> -->

app/views/elders/show.html.erb
<div class="container-show">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-3">

        <div class="elder-single-photo">
          <% if @elder.photo.file %>
            <%= cl_image_tag @elder.photo, height: 300, width: 400, crop: :fill, gravity: :face %>
          <% else %>
            <%= image_tag("https://ak4.picdn.net/shutterstock/videos/5431364/thumb/1.jpg?i10c=img.resize(height:150)") %>
          <% end %>
        </div>
      </div>

      <div class="col-xs-12 col-sm-7">
        <div class="elder-specs-wrapper">

          <div class="elder-description">
            <h5><%= @elder.full_name%></h5>
            <p><i class="fas fa-map-marker-alt"></i> <%= @elder.address %></p>
            <p><%= @elder.description %></p>
          </div>

          <div class="elder-skills">
            <h3>Skills</h3>
            <ul class="skills-list">
              <% @elder.skills.each do |skill| %>
                <li>
                  <p><%= skill.name %></p>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-sm-2 booking-form">
        <%= simple_form_for [@elder, @rent], wrapper_html: { class: "form-group" } do |f| %>
          <%= f.input :start_date, as: :string, input_html: {class: "datepicker"}  %>
          <%= f.input :end_date, as: :string, input_html: {class: "datepicker"} %>
          <%= f.button :submit, {class: "btn btn-primary btn-sm"}%>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container-reviews">
  <% elder = Elder.find(params[:id]) %>
  <% if elder.average_rating == "" %>
    <h3>Be the first one to review <%= elder.full_name %> </h3>
  <% else %>
    <h3>Average rate: <%= '⭐️' * Elder.find(params[:id]).average_rating %></h3>
  <% end %>

  <% @elder.rents.each do |rent|%>
    <%= render 'reviews', rent: rent %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>GrandPa-Rent</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>
  <body style="margin-top: 70px">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/layouts/layout_home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>GrandPa-Rent</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body >
    <%= render 'shared/navbar_home_white' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        Il faut bien que vieillesse se passe <i class="fas fa-heart"></i>
      </div>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/my/elders/_form.html.erb
<%= simple_form_for [:my, elder] do |f| %>
  <%= f.input :full_name, label: 'Your Elder should have an uniq full_name', error: 'Please read the abovementionned criteria' %>
  <%= f.input :address, label: 'We should be able to locate you Elder', error: 'Please read the abovementionned criteria' %>
  <%= f.input :description, label: 'Could be nice to describe this old thing' %>
  <%= f.input :photo, label: 'Add a picture' %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.input :skill_ids, collection: Skill.all, input_html: {multiple: true, class: 'select2'}, include_hidden: false, label: 'Why should I pick your Elder?' %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/my/elders/edit.html.erb
<div class="container">
  <h1>Edit this Old Person</h1>
  <hr>
  <%= render 'form', elder: @elder %>
</div>

app/views/my/elders/index.html.erb
<div class="text-center">
  <h2>Manage my Elders</h2>
  <br>
  <%= link_to 'Add an Elder', new_my_elder_path, class: "btn btn-primary" %>
  <hr>
</div>

<div class="container">
  <div class="row align">
    <% @elders.each do |elder| %>
      <div class="message" >
        <div class="col-xs-1 col-sm-1 message-avatar">
          <%= cl_image_tag elder.photo, height: 300, width: 300, crop: :fill , class: "avatar-large"  %>
        </div>
        <div class="col-xs-9 col-sm-9 message-body">
          <h3 style="display: inline;"><%= elder.full_name %> </h3>
          <h6 style="display: inline;">- <%= elder.address %></h6>
          <p><%= elder.description  %></p>
          <% skills = [] %>
          <% elder.skills.each do |skill| %>
            <% skills << skill.name %>
          <% end %>
          <% skills %>
          <p>
            <%= skills.join(', ') %>
          </p>
        </div>
        <div class="col-xs-1 col-sm-2 message-status">
          <%= link_to edit_my_elder_path(elder) do %>
            <i class="fa fa-pen" aria-hidden="true"> Edit it </i>
          <% end %>
          <br>
          <%= link_to my_elder_path(elder), method: :delete, data: { confirm: "Are you certain you want to DESTROY this poor old person?"} do  %>
            <i class="fa fa-trash" aria-hidden="true"> Destroy it </i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/my/elders/new.html.erb
<div class="container">
  <h1>Add a Nice & Old Fellow</h1>
  <hr>
  <%= render 'form', elder: @elder %>
</div>

app/views/my/rents/index.html.erb
<div class="container text-center">
  <h1>Manage my Bookings</h1>
  <hr>
  <% @bookings.each do |booking| %>
    <div class="message">
      <div class="message-name">
        <h3><%= booking.elder.full_name %></h3>
        <p>Start: <%= booking.start_date %></p>
        <p>End: <%= booking.end_date %></p>
      </div>
      <div class="message-body">
        <p><strong>Description of you Old Thing:</strong></p>
        <p><%= booking.elder.description %></p>
      </div>

      <div class="confirmation">
        <div class="message-status">
          <% if booking.status.capitalize == 'Declined' %>
            <p class='declined'><%= booking.status %></p>
          <% elsif booking.status.capitalize == 'Confirmed' %>
            <p class="confirmed"><%= booking.status %></p>
          <% else %>
            <div class="confirmation-buttons">
              <%= link_to my_rent_confirmeds_path(booking), method: :post, class: "confirmation-btn" do %>
                <button class="btn btn-success">Confirm</button>
              <% end %>
              <%= link_to my_rent_declineds_path(booking), method: :post, class: "decline-btn" do %>
                <button class="btn btn-danger" value="">Decline</button>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/rents/index.html.erb
<div class="text-center">
  <h2>My Rents</h2>
  <br>
  <hr>

  <div class="container">
    <div class="row align">
      <% @rents.reverse_each do |rent| %>
        <% elder = Elder.find(rent.elder_id) %>
        <div class="message-rent" >
          <div class="col-xs-1 col-sm-1">
            <%= cl_image_tag elder.photo, height: 300, width: 300, crop: :fill , class: "avatar-large"  %>
          </div>
          <div class="col-xs-9 col-sm-9 message-rent-body">
            <div class="text-left">
              <h3>
                <%= elder.full_name %>
              </h3>
              <p> Loué du <%= rent.start_date %> au <%= rent.end_date %></p>
            </div>
            <div class="text-right">
              <% today = DateTime.now %>
              <% if rent.status.downcase == 'declined' || rent.status.downcase == 'pending' %>
                <% '' %>
              <% elsif today > rent.end_date && rent.review.nil? %>
                <%= link_to new_rent_review_path(rent) do %>
                  <i class="fa fa-star" aria-hidden="true"> Add a review! </i>
                <% end %>
              <% else today > rent.end_date %>
                <p>Your review has been successfully added</p>
              <% end %>
            </div>
          </div>
          <div class="col-xs-1 col-sm-2 message-rent-status">
            <% if rent.status.capitalize == 'Declined' %>
              <p class='declined'><%= rent.status %></p>
            <% elsif rent.status.capitalize == 'Confirmed' %>
              <p class="confirmed"><%= rent.status %></p>
            <% else %>
              <p class="pending"><%= rent.status %></p>
            <% end %>
          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">

    <div class="col-sm-offset-3 col-sm-6">
      <h2>How was your Grandpa-rent? </h2>
       <div class="row">
          <div class="col-sm-offset-4 col-sm-7">
            <img src="https://i.dlpng.com/static/png/1359741-when-i-finished-my-presentation-on-finding-your-passionate-purpose-this-morning-one-of-the-old-man-png-5616_3744_preview.png " alt="test" height = '100' width="150">
          </div>
      </div>

      <%= simple_form_for @rent, url: rent_reviews_path(@rent), method: :post do |f| %>
        <%= f.input :review, input_html: { class: 'special'}, placeholder: "Please give us your opinion about your elder!" %>
        <%= f.input :rating, collection: 0..5%>
        <%= f.button :submit %>
      <% end %>

    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon transparent">
  <!-- Logo -->
  <div class="circular-landscape">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo-grandma.png", height: 50 %>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "My Rents", rents_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "https://i.kym-cdn.com/photos/images/masonry/000/731/939/d62.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "Manage my Elders", my_elders_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>
            <li>
              <%= link_to "Manage my Bookings", my_rents_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "My Rents", rents_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Manage my Elders", my_elders_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Manage my Bookings", my_rents_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_home_white.html.erb
<div class="navbar-wagon transparent">
  <!-- Logo -->
  <div>
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo-grandma-white.png", height: 50 %>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "My Rents", rents_path, class: "navbar-wagon-item navbar-wagon-link white" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "https://i.kym-cdn.com/photos/images/masonry/000/731/939/d62.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "Manage my Elders", my_elders_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>
            <li>
              <%= link_to "Manage my Bookings", my_rents_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link-login" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "My Rents", rents_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Manage my Elders", my_elders_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Manage my Bookings", my_rents_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>